version: '3'

services:
  db:
    image: mysql
    container-name: db_projet1
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      -dev
  
  phpmyadmin:
    image: phpmyadmin
    container-name: phpmyadmin_projet1
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_HOST: db
    networks: 
      - dev



networks:
  dev:

volumes:
  db-data: